name = "newsfeed-ai-web"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]
preview_urls = false

main = "dist/index.js"

assets = { directory = "dist/assets" }

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[env.production]
routes = [{ pattern = "newsfeed-ai.ryo-o.dev", custom_domain = true }]
